### ISSUE TITLE
Utility fails when security policy set is not configured 

### ISSUE THREAD

**Issue by ktanushree** [ebob9/cloudgenix-idname#10]
When security policy set is not configured on the tenant, cloudgenix_idname utility fails. See snippet below.

idnamedict = cloudgenix_idname.generate_id_name_map(cgx_session)
  File "/Users/tanushreekamath/anaconda2/lib/python2.7/site-packages/cloudgenix_idname/__init__.py", line 491, in generate_id_name_map
    securitypolicyset_id_list = securitypolicyset_to_name_dict(sdk)
ValueError: need more than 2 values to unpack

**Comment by ebob9** [comment]
fixed by 7bae95b13fe80f9e25a1476e222abd0916cb25af
